### ISSUE TITLE
Could you update version of nuxt and argon?

### ISSUE THREAD

**Issue by iorphx** [sambrezo/vue-argon-design-system-nuxt#1]
There's Nuxt v2.8.1 and Vue Argon 1.1.0 released. If you update these it could be appreciated.

**Comment by sambrezo** [comment]
Thanks for taking interest in the project. I updated to Nuxt v2.8.1 and Vue Argon 1.1.0 with 482253f. Currently available in dev branch. I will update the master branch once I am done with testing.

**Comment by iorphx** [comment]
Thanks for fast update and response :)
