### ISSUE TITLE
Problem start app

### ISSUE THREAD

**Issue by NikitaSd1** [sambrezo/vue-argon-design-system-nuxt#5]
Hi, i've got a problem start app. 
I install dependencies **npm install** I got an error

> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@2.1.2
npm WARN optional Skipping failed optional dependency /watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.11
npm WARN optional Skipping failed optional dependency /nodemon/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.11
npm WARN bootstrap@4.4.1 requires a peer of jquery@1.9.1 - 3 but none was installed.
npm WARN eslint-config-prettier@5.1.0 requires a peer of eslint@>=3.14.1 but none was installed.
npm WARN eslint-plugin-prettier@3.1.0 requires a peer of eslint@>= 5.0.0 but none was installed.

After **npm run dev**
[https://imgur.com/a/zIAhMa3](https://imgur.com/a/zIAhMa3)

Can anyone help me?
Thanks for help.

**Comment by sambrezo** [comment]
This is possibly due to a bootstrap incompatibility with Argon Design System. Thanks for reporting. I will look into it.

**Comment by NikitaSd1** [comment]
Okey, thanks

**Comment by smesterheide** [comment]
Sorry, but I could not reproduce the issue. As long as you stick to the bootstrap version in package-lock.json SASS should still compile. Please note however that the repo is no longer supported. Your safest bet is to use the offical Vue Argon Design System.
