### ISSUE TITLE
Could you add a separate repo that doesnt use Bootstrap-Vue

### ISSUE THREAD

**Issue by slidenerd** [sambrezo/vue-argon-design-system-nuxt#7]
- Thank you for adding this repo
- I am not sure why bootstrap-vue is needed for any of this
- Would it be possible for you to add another repo that only uses bootstrap scss files with argon

**Comment by smesterheide** [comment]
You are right, bootstrap-vue is only used for certain features like the carousel. If you can identify which components exactly rely on bootstrap-vue, you can disable them and get rid of the dependency.
I decided to deprecate this repo, so you're on your own there.
